version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "19:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: css-loader
    versions:
    - 5.0.1
    - 5.0.2
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 5.2.1
    - 5.2.2
  - dependency-name: acme-client
    versions:
    - 4.1.2
  - dependency-name: bcrypt
    versions:
    - 5.0.0
  - dependency-name: webpack-node-externals
    versions:
    - 2.5.2
